### ISSUE TITLE
Cannot load such file -- fastlane

### ISSUE THREAD

**Issue by cosminstirbu** [KrauseFx/trainer#16]
I've installed trainer using bundler (I have this in my Gemfile: gem 'trainer', '0.7.0')

When I try to run it: `bundle exec trainer --help`

I receive the following error:

```
LoadError: cannot load such file -- fastlane
  /Users/cosminstirbu/api-sdk-ios/ruby/2.2.0/gems/trainer-0.7.0/lib/trainer.rb:1:in `require'
  /Users/cosminstirbu/api-sdk-ios/ruby/2.2.0/gems/trainer-0.7.0/lib/trainer.rb:1:in `<top (required)>'
  /Users/cosminstirbu/api-sdk-ios/ruby/2.2.0/gems/trainer-0.7.0/bin/trainer:4:in `require'
  /Users/cosminstirbu/api-sdk-ios/ruby/2.2.0/gems/trainer-0.7.0/bin/trainer:4:in `<top (required)>'
  /Users/cosminstirbu/api-sdk-ios/ruby/2.2.0/bin/trainer:23:in `load'
  /Users/cosminstirbu/api-sdk-ios/ruby/2.2.0/bin/trainer:23:in `<top (required)>'
```

**Comment by KrauseFx** [comment]
Can you share your Gemfile and Gemfile.lock?

**Comment by cosminstirbu** [comment]
I've attached both as a .zip file

[Archive.zip](https://github.com/KrauseFx/trainer/files/1334811/Archive.zip)

**Comment by KrauseFx** [comment]
Yah, so `fastlane` is missing there, make sure to add `fastlane` to your Gemfile 👍

**Comment by cosminstirbu** [comment]
But then we should update the documentation, since on https://rubygems.org/gems/trainer the only runtime dependency is https://rubygems.org/gems/plist.

Also, does it really need to depend on fastlane?

**Comment by KrauseFx** [comment]
Right, can you try adding it and see if it works? I can't remember the reason again, but I think that should fix it

**Comment by cosminstirbu** [comment]
You're right, if I add it, it works. Thank you.

**Comment by jmoody** [comment]
I also see this problem.  I want to use this gem without fastlane.

**Comment by jmoody** [comment]
Fastline is a requirement of this gem, but it is listed as a _development_ requirement in the gemspec.

I can see that in the `trainer/commands_generator` there is a reference to FastlaneCore.

This gem does depend on fastlane.

Should the README and gemspec be updated?  Or should this gem be able to stand on its own without fastlane?

**Comment by KrauseFx** [comment]
I think that's because otherwise you end up in a dependency circle, but I might recall this wrong.
